version: '3.8'

services:
  mongodb:
    image: mongo:6.0-jammy
    environment:
      # Set Timezone if necessary
      # TZ: Asia/Tokyo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata:/data/db
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

